version: '3.3'

services:
    rmq:
        image: rabbitmq:latest
        environment: 
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
            
    postgres_db:
        image: postgres:alpine
        environment: 
            - POSTGRES_DB=${SQL_DB_NAME}
            - POSTGRES_USER=${SQL_DB_USER}
            - POSTGRES_PASSWORD=${SQL_DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    api:
        build: ./api
        command: python /opt/tochka-api/manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        depends_on: 
            - rmq
            - postgres_db

    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - api

    celery:
        build: ./api
        command: celery -A config worker -l info
        env_file: 
            - .env
        depends_on: 
            - api
            - rmq

volumes: 
    postgres_data:
    log_data:
