# Generated by Django 3.1.1 on 2020-09-24 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=150)),
                ('balance', models.IntegerField()),
                ('hold', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
